// This file is automatically generated by scripts/GetYoutueData.py
// Do not edit manually - it will be overwritten

export const youtubeVideos = [
  {
    title: "Hierarchical Reasoning Models",
    description: "Paper: https://arxiv.org/abs/2506.21734\nCode! https://github.com/sapientinc/HRM\n\nNotes: https://drive.google.com/file/d/1Y6_fBzC0TUo-4xZyq6MC6ZmYateKjRU-/view?usp=drive_link\n\n00:00 Intro\n04:27 Method\n...",
    videoId: "TUsbk8vPDoM",
    thumbnail: "https://img.youtube.com/vi/TUsbk8vPDoM/maxresdefault.jpg",
    duration: "42:04",
    publishedAt: "2025-08-09",
    views: "10.6K",
    likes: "380"
  },
  {
    title: "Energy-Based Transformers are Scalable Learners and Thinkers",
    description: "Paper: https://arxiv.org/abs/2507.02092\nCode! https://energy-based-transformers.github.io/\n\nNotes: https://drive.google.com/file/d/1Sb5jwO3X0xCSVMcEiukYtOuSvyam6Aog/view?usp=drive_link\n\n00:00 Intro\n03...",
    videoId: "uUE0x3iNX1U",
    thumbnail: "https://img.youtube.com/vi/uUE0x3iNX1U/maxresdefault.jpg",
    duration: "39:06",
    publishedAt: "2025-07-14",
    views: "2.2K",
    likes: "79"
  },
  {
    title: "Fast and Simplex: 2-Simplicial Attention in Triton",
    description: "Paper: https://arxiv.org/abs/2507.02754\n\nNotes: https://drive.google.com/file/d/1RiKsrhgavbpzLurlQDODO6XsGoFhe0IR/view?usp=drive_link\n\n00:00 Intro and some remarks\n03:22 Normal quadratic attention\n09:...",
    videoId: "W-0LSbTnbVc",
    thumbnail: "https://img.youtube.com/vi/W-0LSbTnbVc/maxresdefault.jpg",
    duration: "39:20",
    publishedAt: "2025-07-07",
    views: "1.3K",
    likes: "50"
  },
  {
    title: "Hardware-Efficient Attention for Fast Decoding",
    description: "Paper: https://arxiv.org/abs/2505.21487\n\nNotes: https://drive.google.com/file/d/1NdoVyRIjA-I30fJVruDZpPAnxS8I38R6/view?usp=drive_link\nDiagrams: https://drive.google.com/file/d/1Ni5Swx28SV3qS6r4i2iqoBX...",
    videoId: "oHkMoQi8Z7M",
    thumbnail: "https://img.youtube.com/vi/oHkMoQi8Z7M/maxresdefault.jpg",
    duration: "40:58",
    publishedAt: "2025-06-30",
    views: "1.1K",
    likes: "57"
  },
  {
    title: "ATLAS: Learning to Optimally Memorize the Context at Test Time",
    description: "Paper: https://arxiv.org/abs/2505.23735\n\nPaper Notes: https://drive.google.com/file/d/1PQ0L-qCRkPTxwTKtssyqMeRRKyNZXLHa/view?usp=drive_link\nOther Notes: https://drive.google.com/file/d/1POBcHgauiMX_NB...",
    videoId: "cNfX1aRr9Hg",
    thumbnail: "https://img.youtube.com/vi/cNfX1aRr9Hg/maxresdefault.jpg",
    duration: "59:58",
    publishedAt: "2025-06-23",
    views: "1.1K",
    likes: "42"
  },
  {
    title: "Coding Stable Diffusion 3 From Scratch",
    description: "Going through some code I wrote to train stable diffusion 3. \nCode can be found here: https://github.com/gmongaras/Stable-Diffusion-3-From-Scratch\n0:00:00 Intro\n0:02:46 Data, not fun but necessary\n0:2...",
    videoId: "S19zbVz3EYs",
    thumbnail: "https://img.youtube.com/vi/S19zbVz3EYs/maxresdefault.jpg",
    duration: "2:07:02",
    publishedAt: "2025-06-02",
    views: "2.3K",
    likes: "126"
  },
  {
    title: "Intro to Attention and Its Forms",
    description: "Presentation Link: https://docs.google.com/presentation/d/1SqNom5wgzyK6M7MzpjN02-B3KuDgtlXEV6B-Fckt2Sc/edit?usp=sharing\n\n00:00 Intro\n04:35 Attention Definition and Intuition\n15:06 Self Attention (bidi...",
    videoId: "IR8PqmGTGyw",
    thumbnail: "https://img.youtube.com/vi/IR8PqmGTGyw/maxresdefault.jpg",
    duration: "2:13:00",
    publishedAt: "2025-04-22",
    views: "3.4K",
    likes: "210"
  },
  {
    title: "RWKV-7 \"Goose\" with Expressive Dynamic State Evolution",
    description: "Paper: https://arxiv.org/abs/2503.14456\n\nPaper Notes: https://drive.google.com/file/d/13sORm4tjWYFH4uqZi9aqP3Nrcvlveb9V/view?usp=sharing\nDiagram and Equation Notes: https://drive.google.com/file/d/1Sv...",
    videoId: "Vz_ud4x0YDs",
    thumbnail: "https://img.youtube.com/vi/Vz_ud4x0YDs/maxresdefault.jpg",
    duration: "47:18",
    publishedAt: "2025-03-21",
    views: "1.4K",
    likes: "69"
  },
  {
    title: "Scaling up Test-Time Compute with Latent Reasoning: A Recurrent Depth Approach",
    description: "Paper: https://arxiv.org/abs/2502.05171\nCode! https://github.com/seal-rg/recurrent-pretraining\n\nNotes: https://drive.google.com/file/d/10WQ_4EtZdnVpxuVNoCzYhzkH8ujtQu8S/view?usp=drive_link\nhttps://dri...",
    videoId: "HRIsAFmzNjg",
    thumbnail: "https://img.youtube.com/vi/HRIsAFmzNjg/maxresdefault.jpg",
    duration: "29:33",
    publishedAt: "2025-02-26",
    views: "2.0K",
    likes: "76"
  },
  {
    title: "Native Sparse Attention: Hardware-Aligned and Natively Trainable Sparse Attention",
    description: "Paper: https://arxiv.org/abs/2502.11089\n\nNotes: https://drive.google.com/open?id=1HLEM4m77-C8HqEBoKpk6mnpngIjUB5jR&usp=drive_copy\n\n00:00 Intro\n01:30 Sparse attention\n05:48 Token compression attention\n...",
    videoId: "ReA6pSSDzLk",
    thumbnail: "https://img.youtube.com/vi/ReA6pSSDzLk/maxresdefault.jpg",
    duration: "40:08",
    publishedAt: "2025-02-21",
    views: "5.4K",
    likes: "182"
  },
  {
    title: "VideoJAM: Joint Appearance-Motion Representations for Enhanced Motion Generation in Video Models",
    description: "Paper: https://arxiv.org/abs/2502.02492\n\nMy notes: https://drive.google.com/file/d/11sWvavz2jS6e_qvyoee5u2lJD6t7CEr8/view?usp=sharing\n\n00:00 Intro\n00:51 Current video models\n06:15 Problem with normal ...",
    videoId: "8nZbTvES11Y",
    thumbnail: "https://img.youtube.com/vi/8nZbTvES11Y/maxresdefault.jpg",
    duration: "28:26",
    publishedAt: "2025-02-07",
    views: "915",
    likes: "28"
  },
  {
    title: "DeepSeek-V3",
    description: "Paper: https://arxiv.org/abs/2412.19437v1\nR1 paper: https://arxiv.org/abs/2501.12948\nDeepSeekMoe: https://arxiv.org/abs/2401.06066\nHuggingface: https://huggingface.co/deepseek-ai\n\nNotes: https://drive...",
    videoId: "8v2l6SJECW4",
    thumbnail: "https://img.youtube.com/vi/8v2l6SJECW4/maxresdefault.jpg",
    duration: "1:21:39",
    publishedAt: "2025-01-29",
    views: "26.8K",
    likes: "882"
  },
  {
    title: "Titans: Learning to Memorize at Test Time",
    description: "Paper: https://arxiv.org/abs/2501.00663\n\nNotes: https://drive.google.com/file/d/1EUgTvvcRo_kjX8IjKufkphCG4CtEVYql/view?usp=drive_link\n\n00:00 Intro\n01:30 Linear attention\n15:04 Lightning attention\n29:1...",
    videoId: "lWgFuHy_m-c",
    thumbnail: "https://img.youtube.com/vi/lWgFuHy_m-c/maxresdefault.jpg",
    duration: "59:24",
    publishedAt: "2025-01-24",
    views: "3.4K",
    likes: "126"
  },
  {
    title: "MiniMax-01: Scaling Foundation Models with Lightning Attention",
    description: "MiniMax-01: https://arxiv.org/abs/2501.08313\nLightning attention: https://arxiv.org/abs/2405.17381\nLightning attention v2: https://arxiv.org/abs/2401.04658\n\nLightning attention code: https://github.co...",
    videoId: "9a7Ddy8mL58",
    thumbnail: "https://img.youtube.com/vi/9a7Ddy8mL58/maxresdefault.jpg",
    duration: "48:21",
    publishedAt: "2025-01-16",
    views: "1.8K",
    likes: "69"
  },
  {
    title: "Memory Layers at Scale",
    description: "Paper: https://arxiv.org/abs/2412.09764\nCode: https://github.com/facebookresearch/memory\nBlog: https://ai.meta.com/blog/meta-fair-updates-agents-robustness-safety-architecture\n\nNotes: https://drive.go...",
    videoId: "zWXxPWcfuc8",
    thumbnail: "https://img.youtube.com/vi/zWXxPWcfuc8/maxresdefault.jpg",
    duration: "46:17",
    publishedAt: "2025-01-08",
    views: "1.5K",
    likes: "50"
  },
  {
    title: "Byte Latent Transformer: Patches Scale Better Than Tokens",
    description: "Paper here: https://arxiv.org/abs/2412.09871\nCode: https://github.com/facebookresearch/blt\n\nNotes: \nhttps://drive.google.com/file/d/1B5BdO9FtmxTJiWwVJ3Wa-v3pqaRdbWMh/view?usp=drive_link\nhttps://drive....",
    videoId: "NzMDCXT5ZcE",
    thumbnail: "https://img.youtube.com/vi/NzMDCXT5ZcE/maxresdefault.jpg",
    duration: "45:05",
    publishedAt: "2024-12-18",
    views: "3.1K",
    likes: "123"
  },
  {
    title: "Scaling up Masked Diffusion Models on Text",
    description: "Paper here: https://arxiv.org/abs/2410.18514\nCode: https://github.com/ML-GSAI/SMDM\n\nNotes: https://drive.google.com/file/d/19n24Quv_ZoLGO8epowB3ImmLHbAeUYWC/view?usp=drive_link\n\n00:00 Intro\n06:54 Meth...",
    videoId: "ZL1atsNd6yI",
    thumbnail: "https://img.youtube.com/vi/ZL1atsNd6yI/maxresdefault.jpg",
    duration: "40:03",
    publishedAt: "2024-12-08",
    views: "1.0K",
    likes: "38"
  },
  {
    title: "TokenFormer: Rethinking Transformer Scaling with Tokenized Model Parameters",
    description: "Paper here: https://arxiv.org/abs/2410.23168\nCode: https://github.com/haiyang-w/tokenformer\n\nNotes: https://drive.google.com/file/d/17PsGwefQJoSQxBHykoSFeMrKZhPDFx-E/view?usp=sharing\n\n00:00 Intro\n02:4...",
    videoId: "4lGgbkD6Z0I",
    thumbnail: "https://img.youtube.com/vi/4lGgbkD6Z0I/maxresdefault.jpg",
    duration: "25:22",
    publishedAt: "2024-11-05",
    views: "1.8K",
    likes: "67"
  },
  {
    title: "Round and Round We Go! What makes Rotary Positional Encodings useful?",
    description: "Paper here: https://arxiv.org/abs/2410.06205\n\nNotes: https://drive.google.com/file/d/152NPPyNjo-N6MMIaupXacS41BUJgjE5l/view?usp=drive_link\n\n00:00 Intro\n01:09 RoPE: Rotary Positional Embeddings\n10:37 N...",
    videoId: "2tS_bXPoriI",
    thumbnail: "https://img.youtube.com/vi/2tS_bXPoriI/maxresdefault.jpg",
    duration: "32:31",
    publishedAt: "2024-10-18",
    views: "1.9K",
    likes: "71"
  },
  {
    title: "Deterministic Image Editing with DDPM Inversion, DDIM Inversion, Null Inversion and Prompt-to-Prompt",
    description: "Null-text Inversion for Editing Real Images using Guided Diffusion Models: https://arxiv.org/abs/2211.09794\n\nAn Edit Friendly DDPM Noise Space: Inversion and Manipulations: https://arxiv.org/abs/2304....",
    videoId: "YssE-7D029Y",
    thumbnail: "https://img.youtube.com/vi/YssE-7D029Y/maxresdefault.jpg",
    duration: "1:13:09",
    publishedAt: "2024-07-31",
    views: "3.1K",
    likes: "112"
  },
  {
    title: "Attending to Topological Spaces: The Cellular Transformer",
    description: "Paper here: https://arxiv.org/abs/2405.14094\n\nNotes: https://drive.google.com/file/d/12g_KkHqXD6mEDILJzYbCC08i8cDHITfC/view?usp=drive_link\n\n00:00 Intro\n01:39 Cellular complexes\n07:26 K-cochain\n13:26 D...",
    videoId: "ParHL03RL5g",
    thumbnail: "https://img.youtube.com/vi/ParHL03RL5g/maxresdefault.jpg",
    duration: "42:25",
    publishedAt: "2024-07-22",
    views: "818",
    likes: "33"
  },
  {
    title: "Learning to (Learn at Test Time): RNNs with Expressive Hidden States",
    description: "Paper here: https://arxiv.org/abs/2407.04620\nCode!: https://github.com/test-time-training/ttt-lm-pytorch\n\nNotes: https://drive.google.com/file/d/127a1UBm_IN_WMKG-DmEvfJ8Pja-9BwDk/view?usp=drive_link\n\n...",
    videoId: "I9Ghw2Z7Gqk",
    thumbnail: "https://img.youtube.com/vi/I9Ghw2Z7Gqk/maxresdefault.jpg",
    duration: "35:51",
    publishedAt: "2024-07-12",
    views: "4.3K",
    likes: "128"
  },
  {
    title: "WARP: On the Benefits of Weight Averaged Rewarded Policies",
    description: "Paper here: https://arxiv.org/abs/2406.16768\n\nNotes: https://drive.google.com/file/d/11UK7mEZwNVUMYuXwvOTfaqHhN8zSYm5M/view?usp=drive_link\n\n00:00 Intro and RLHF\n17:30 Problems with RLHF\n21:08 Overview...",
    videoId: "utsnn06TBlM",
    thumbnail: "https://img.youtube.com/vi/utsnn06TBlM/maxresdefault.jpg",
    duration: "52:38",
    publishedAt: "2024-07-06",
    views: "823",
    likes: "32"
  },
  {
    title: "CoDeF: Content Deformation Fields for Temporally Consistent Video Processing",
    description: "Paper: https://arxiv.org/abs/2308.07926\nPaper page: https://qiuyu96.github.io/CoDeF/\nCode: https://github.com/qiuyu96/CoDeF\n\nMy notes: https://drive.google.com/file/d/10PMKdd5XBd6Y60HlRB9IW9naR2bWziDT...",
    videoId: "5mQLaa5XdgM",
    thumbnail: "https://img.youtube.com/vi/5mQLaa5XdgM/maxresdefault.jpg",
    duration: "28:52",
    publishedAt: "2024-06-25",
    views: "910",
    likes: "44"
  },
  {
    title: "Mamba 2 - Transformers are SSMs: Generalized Models and Efficient Algorithms Through SSS Duality",
    description: "Paper here: https://arxiv.org/abs/2405.21060\nCode!: https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mamba2.py\n\nNotes: https://drive.google.com/file/d/1--XGPFeXQyx4CPxgYjzR4qrLd-baLWQ...",
    videoId: "EtnSexLgQMc",
    thumbnail: "https://img.youtube.com/vi/EtnSexLgQMc/maxresdefault.jpg",
    duration: "1:14:42",
    publishedAt: "2024-06-16",
    views: "13.5K",
    likes: "357"
  },
  {
    title: "CoPE - Contextual Position Encoding: Learning to Count What's Important",
    description: "Paper: https://arxiv.org/abs/2405.18719\n\nMy notes: https://drive.google.com/file/d/1y9VHZc7MLqc6t2SHHdlVTYeW3czmmRbl/view?usp=sharing\n\n00:00 Intro\n02:44 Background\n09:58 CoPE\n24:50 Code\n32:16 Results",
    videoId: "qcMsvU-wYZA",
    thumbnail: "https://img.youtube.com/vi/qcMsvU-wYZA/maxresdefault.jpg",
    duration: "38:55",
    publishedAt: "2024-06-04",
    views: "1.6K",
    likes: "49"
  },
  {
    title: "NaturalSpeech 3: Zero-Shot Speech Synthesis with Factorized Codec and Diffusion Models",
    description: "Paper: https://arxiv.org/abs/2403.03100\nDemo: https://speechresearch.github.io/naturalspeech3/\nCode: https://huggingface.co/spaces/amphion/naturalspeech3_facodec\n\nMy notes: https://drive.google.com/fi...",
    videoId: "-BelefxpVc8",
    thumbnail: "https://img.youtube.com/vi/-BelefxpVc8/maxresdefault.jpg",
    duration: "45:48",
    publishedAt: "2024-05-28",
    views: "1.1K",
    likes: "48"
  },
  {
    title: "xLSTM: Extended Long Short-Term Memory",
    description: "Paper: https://arxiv.org/abs/2405.04517\n\nMy notes: https://drive.google.com/file/d/1wFYvU_1oUWcCNuQ91zTpSGAeNUsPjlt3/view?usp=drive_link\n\n00:00 Intro\n05:44 LSTM\n13:38 Problems paper addresses\n14:12 sL...",
    videoId: "4ND8lU2aN_k",
    thumbnail: "https://img.youtube.com/vi/4ND8lU2aN_k/maxresdefault.jpg",
    duration: "43:26",
    publishedAt: "2024-05-17",
    views: "2.4K",
    likes: "85"
  },
  {
    title: "KAN: Kolmogorov-Arnold Networks",
    description: "Paper: https://arxiv.org/abs/2404.19756\n\nSpline Video: https://m.youtube.com/watch?v=qhQrRCJ-mVg\n\nMy notes: https://drive.google.com/file/d/1twcIF13nG8Qc10_qeDqCZ4NaUh9tFsAH/view?usp=drive_link\n\n00:00...",
    videoId: "CkCijaXqAOM",
    thumbnail: "https://img.youtube.com/vi/CkCijaXqAOM/maxresdefault.jpg",
    duration: "37:08",
    publishedAt: "2024-05-04",
    views: "58.0K",
    likes: "1.8K"
  },
  {
    title: "LADD: Fast High-Resolution Image Synthesis with Latent Adversarial Diffusion Distillation",
    description: "Paper: https://arxiv.org/abs/2403.12015\n\nMy notes: https://drive.google.com/file/d/1s1-nnWR_ZR26PNSAoZR1Xj3nuD9UZlvR/view?usp=sharing\n\n00:00 Intro\n01:31 Diffusion Models\n08:08 Latent Diffusion Models\n...",
    videoId: "9T352z1woNc",
    thumbnail: "https://img.youtube.com/vi/9T352z1woNc/maxresdefault.jpg",
    duration: "30:06",
    publishedAt: "2024-04-29",
    views: "1.4K",
    likes: "48"
  },
  {
    title: "Visual AutoRegressive Modeling:Scalable Image Generation via Next-Scale Prediction",
    description: "Paper: https://arxiv.org/abs/2404.02905\nDemo: https://var.vision/\nCode: https://github.com/FoundationVision/VAR\n\nMy notes: https://drive.google.com/file/d/1qym3JG-0xqEgQhdvkt9N17o-ZzUWy2sn/view?usp=dr...",
    videoId: "yJ396Ksiv2s",
    thumbnail: "https://img.youtube.com/vi/yJ396Ksiv2s/maxresdefault.jpg",
    duration: "36:59",
    publishedAt: "2024-04-21",
    views: "7.8K",
    likes: "206"
  },
  {
    title: "Leave No Context Behind: Efficient Infinite Context Transformers with Infini-attention",
    description: "Paper: https://arxiv.org/abs/2404.07143\n\nMy notes: https://drive.google.com/file/d/1plWJDwHTZkRK9PDdvaLMnZjFR6fVvNLH/view?usp=drive_link\n\n00:00 Intro\n07:17 Model intuition\n11:00 Memory retrieval opera...",
    videoId: "MRTTGMlKgb8",
    thumbnail: "https://img.youtube.com/vi/MRTTGMlKgb8/maxresdefault.jpg",
    duration: "32:48",
    publishedAt: "2024-04-14",
    views: "4.0K",
    likes: "119"
  },
  {
    title: "Mixture-of-Depths: Dynamically allocating compute in transformer-based language models",
    description: "Paper: https://arxiv.org/abs/2404.02258\n\nMy notes: https://drive.google.com/file/d/1o4v5te1yfuK_FQPvvS8SR55Sysg04dYK/view?usp=drive_link\n\n00:00 Intro\n06:02 Mixture of Experts (MoE)\n15:12 Mixture of De...",
    videoId: "M8QkiuSto6I",
    thumbnail: "https://img.youtube.com/vi/M8QkiuSto6I/maxresdefault.jpg",
    duration: "40:13",
    publishedAt: "2024-04-08",
    views: "2.4K",
    likes: "79"
  },
  {
    title: "Q* AGI Achieved (Apr Fools)",
    description: "Q* paper link: https://link.springer.com/content/pdf/10.1007/BF00992698.pdf\n\n\n\n\n\n\n\nApril fools 😏",
    videoId: "PTfQGJjI7Lw",
    thumbnail: "https://img.youtube.com/vi/PTfQGJjI7Lw/maxresdefault.jpg",
    duration: "4:53",
    publishedAt: "2024-04-01",
    views: "818",
    likes: "32"
  },
  {
    title: "Stable Diffusion 3: Scaling Rectified Flow Transformers for High-Resolution Image Synthesis",
    description: "Website paper: https://stability.ai/news/stable-diffusion-3-research-paper\nPaper: https://arxiv.org/abs/2403.03206\n\nMy notes: https://drive.google.com/file/d/1n8rSM3OuOkzDBlXdK5VBrnADnEXp4xXv/view?usp...",
    videoId: "6XatajQ-ll0",
    thumbnail: "https://img.youtube.com/vi/6XatajQ-ll0/maxresdefault.jpg",
    duration: "1:02:29",
    publishedAt: "2024-03-28",
    views: "8.2K",
    likes: "249"
  },
  {
    title: "GaLore: Memory-Efficient LLM Training by Gradient Low-Rank Projection",
    description: "My notes: https://drive.google.com/file/d/1l2B4m8tDVchfsplIbps4-9533fcxqubF/view?usp=drive_link\n\nPaper: https://arxiv.org/abs/2403.03507\n\n\n00:00 Intro\n02:44 Intuition and proof of low rank\n12:28 GaLor...",
    videoId: "HwDnArsxGOE",
    thumbnail: "https://img.youtube.com/vi/HwDnArsxGOE/maxresdefault.jpg",
    duration: "37:08",
    publishedAt: "2024-03-21",
    views: "1.2K",
    likes: "31"
  },
  {
    title: "The Era of 1-bit LLMs: All Large Language Models are in 1.58 Bits and BitNet",
    description: "My notes:\nBitNet: https://drive.google.com/file/d/1iA2tISamkfQq4jgZZBBSH1MN3Bgtc99_/view?usp=sharing\nEra of 1-bit LLMs: https://drive.google.com/file/d/1iNy91MTP53kTCSkeqHBqMOSePPyoYvCD/view?usp=shari...",
    videoId: "JnU1Ov9p77M",
    thumbnail: "https://img.youtube.com/vi/JnU1Ov9p77M/maxresdefault.jpg",
    duration: "46:25",
    publishedAt: "2024-03-06",
    views: "6.3K",
    likes: "220"
  },
  {
    title: "DoRA: Weight-Decomposed Low-Rank Adaptation",
    description: "Paper: https://arxiv.org/abs/2402.09353\n\nMy notes: https://drive.google.com/file/d/1hA56lNtz7jxQPWIxBpnDUsiLFaFZlyyP/view?usp=sharing",
    videoId: "m7KQdGSr0Dg",
    thumbnail: "https://img.youtube.com/vi/m7KQdGSr0Dg/maxresdefault.jpg",
    duration: "31:15",
    publishedAt: "2024-02-23",
    views: "2.6K",
    likes: "94"
  },
  {
    title: "OpenAI Sora and DiTs: Scalable Diffusion Models with Transformers",
    description: "Sora: https://openai.com/sora\nSora paper (Video generation models as world simulators): https://openai.com/research/video-generation-models-as-world-simulators\n\nDiTs - Scalable Diffusion Models with T...",
    videoId: "fWUwDEi1qlA",
    thumbnail: "https://img.youtube.com/vi/fWUwDEi1qlA/maxresdefault.jpg",
    duration: "1:02:38",
    publishedAt: "2024-02-18",
    views: "14.5K",
    likes: "423"
  },
  {
    title: "A Decoder-only Foundation Model For Time-series Forecasting",
    description: "Paper: https://arxiv.org/abs/2310.10688\n\nNotes: https://drive.google.com/file/d/1fmk5Z5VJkqHvEbNXlq1OiIBP317NqNfN/view?usp=sharing",
    videoId: "YkzRP3xnMwc",
    thumbnail: "https://img.youtube.com/vi/YkzRP3xnMwc/maxresdefault.jpg",
    duration: "33:55",
    publishedAt: "2024-02-07",
    views: "6.3K",
    likes: "183"
  },
  {
    title: "Lumiere: A Space-Time Diffusion Model for Video Generation",
    description: "Paper: https://arxiv.org/abs/2401.12945\nDemo: https://lumiere-video.github.io/\n\nNotes: https://drive.google.com/file/d/1fJl-ijVy6KML1YwM_9UVVU-MSfipDIqe/view?usp=sharing",
    videoId: "a6McRCEesNs",
    thumbnail: "https://img.youtube.com/vi/a6McRCEesNs/maxresdefault.jpg",
    duration: "37:30",
    publishedAt: "2024-02-02",
    views: "755",
    likes: "24"
  },
  {
    title: "Exphormer: Sparse Transformers for Graphs",
    description: "Paper here: https://arxiv.org/abs/2303.06147\n\nNotes: https://drive.google.com/file/d/1eXoXtPgJYKBTKd7oN8StuBLW453yWJ3f/view?usp=drive_link",
    videoId: "yRfgibfZALU",
    thumbnail: "https://img.youtube.com/vi/yRfgibfZALU/maxresdefault.jpg",
    duration: "28:56",
    publishedAt: "2024-01-29",
    views: "547",
    likes: "24"
  },
  {
    title: "Medusa: Simple Framework for Accelerating LLM Generation with Multiple Decoding Heads",
    description: "Paper here: https://arxiv.org/abs/2401.10774\ndemo: https://sites.google.com/view/medusa-llm\n\nNotes: https://drive.google.com/file/d/1eOminZIC4wrjjWIBnSroxBYduCXzs86E/view?usp=drive_link",
    videoId: "JmYFunlTeVI",
    thumbnail: "https://img.youtube.com/vi/JmYFunlTeVI/maxresdefault.jpg",
    duration: "25:55",
    publishedAt: "2024-01-24",
    views: "2.7K",
    likes: "73"
  },
  {
    title: "Boundary Attention: Learning to Find Faint Boundaries at Any Resolution",
    description: "Paper here: https://arxiv.org/abs/2401.00935\n\nNotes: https://drive.google.com/file/d/1eAiAhbmvczYQwHqHHv-GJeDlX-WlZBBI/view?usp=sharing",
    videoId: "CEoOMDN9g2g",
    thumbnail: "https://img.youtube.com/vi/CEoOMDN9g2g/maxresdefault.jpg",
    duration: "40:22",
    publishedAt: "2024-01-18",
    views: "520",
    likes: "19"
  },
  {
    title: "Cached Transformers: Improving Transformers with Differentiable Memory Cache",
    description: "Paper here: https://arxiv.org/abs/2312.12742\nCode here: https://github.com/annosubmission/GRC-Cache\n\nNotes: https://drive.google.com/file/d/1cgR14tZmrF3lQROMT_2RUig2dBfhqU9z/view?usp=sharing",
    videoId: "DAAcndZl19s",
    thumbnail: "https://img.youtube.com/vi/DAAcndZl19s/maxresdefault.jpg",
    duration: "29:37",
    publishedAt: "2024-01-04",
    views: "916",
    likes: "29"
  },
  {
    title: "Translatotron 3: Speech to Speech Translation with Monolingual Data",
    description: "Translatotron 3: https://arxiv.org/abs/2305.17547\nTranslatotron 2: https://arxiv.org/abs/2107.08661\nDemo: https://google-research.github.io/lingvo-lab/translatotron3/\n\nNotes: \nTranslatotron 3: https:/...",
    videoId: "M8ivrpoLGw8",
    thumbnail: "https://img.youtube.com/vi/M8ivrpoLGw8/maxresdefault.jpg",
    duration: "39:02",
    publishedAt: "2023-12-27",
    views: "1.2K",
    likes: "30"
  },
  {
    title: "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
    description: "Paper here: https://arxiv.org/abs/2312.00752\nThe annotated S4: https://srush.github.io/annotated-s4/\n\nNotes: https://drive.google.com/file/d/1aoaKj3kuTtpHi0OzinXZGyZIFxhqp514/view?usp=sharing",
    videoId: "866SfiCHZ4o",
    thumbnail: "https://img.youtube.com/vi/866SfiCHZ4o/maxresdefault.jpg",
    duration: "44:02",
    publishedAt: "2023-12-12",
    views: "10.4K",
    likes: "310"
  },
  {
    title: "Latent Consistency Models: Synthesizing High-Resolution Images with Few-Step Inference",
    description: "Paper Link: https://arxiv.org/abs/2310.04378\n\nMy Notes: https://drive.google.com/file/d/1aUDxMSWNAqMkg0P91Ms1vu4yCeTtzSsR/view?usp=sharing",
    videoId: "OT3JWNz0Il8",
    thumbnail: "https://img.youtube.com/vi/OT3JWNz0Il8/maxresdefault.jpg",
    duration: "47:32",
    publishedAt: "2023-12-06",
    views: "2.7K",
    likes: "80"
  },
  {
    title: "Adversarial Diffusion Distillation",
    description: "Paper Link: https://arxiv.org/abs/2311.17042\nStability Link: stability.ai/research/adversarial-diffusion-distillation\n\nMy Notes: https://drive.google.com/file/d/1a7EZpQ-4_jjt7Fic1EQlyGnHOX1xB9Af/view?...",
    videoId: "ZxPQtXu1Wbw",
    thumbnail: "https://img.youtube.com/vi/ZxPQtXu1Wbw/maxresdefault.jpg",
    duration: "28:38",
    publishedAt: "2023-11-30",
    views: "2.3K",
    likes: "69"
  },
  {
    title: "Unsupervised Discovery of Semantic Latent Directions in Diffusion Models",
    description: "Paper found here: https://arxiv.org/abs/2302.12469\nMy notes: https://drive.google.com/file/d/1_wFtrtxZk7ZYq6-FfUILET3Nga8KCzsz/view?usp=drive_link",
    videoId: "Ow8kKv8ely8",
    thumbnail: "https://img.youtube.com/vi/Ow8kKv8ely8/maxresdefault.jpg",
    duration: "40:51",
    publishedAt: "2023-11-21",
    views: "780",
    likes: "29"
  },
  {
    title: "DALL-E 3 - Improving Image Generation with Better Captions",
    description: "Blog post here: https://openai.com/dall-e-3\nMy notes: https://drive.google.com/file/d/1_lSM24dNSdzAvP8MKaKIyfbsASn4UfYe/view?usp=sharing",
    videoId: "2NmRJxaUwyE",
    thumbnail: "https://img.youtube.com/vi/2NmRJxaUwyE/maxresdefault.jpg",
    duration: "18:45",
    publishedAt: "2023-11-20",
    views: "678",
    likes: "30"
  },
  {
    title: "LRM: Large Reconstruction Model for Single Image to 3D",
    description: "Paper found here: https://arxiv.org/abs/2311.04400\nMy notes: https://drive.google.com/file/d/1_cI6cYIm8QZrv0lhfYBG7ULXc4szr8Hg/view?usp=sharing",
    videoId: "RD-UhM1kBVY",
    thumbnail: "https://img.youtube.com/vi/RD-UhM1kBVY/maxresdefault.jpg",
    duration: "38:17",
    publishedAt: "2023-11-13",
    views: "2.1K",
    likes: "46"
  },
  {
    title: "CodeFusion: A Pre-trained Diffusion Model for Code Generation",
    description: "Paper found here: https://arxiv.org/abs/2310.17680v1\nMy chicken scratch: https://drive.google.com/file/d/1ErA6RsKW__uxmlprgdIO13PRCU69Q-U5/view?usp=drive_link",
    videoId: "jdupXLVpRNg",
    thumbnail: "https://img.youtube.com/vi/jdupXLVpRNg/maxresdefault.jpg",
    duration: "30:45",
    publishedAt: "2023-11-06",
    views: "876",
    likes: "33"
  },
  {
    title: "Matryoshka Diffusion Models Explained",
    description: "Paper found here: https://arxiv.org/abs/2310.15111",
    videoId: "WY_vxDTHUVo",
    thumbnail: "https://img.youtube.com/vi/WY_vxDTHUVo/maxresdefault.jpg",
    duration: "22:14",
    publishedAt: "2023-10-30",
    views: "727",
    likes: "36"
  },
  {
    title: "UniAudio: An Audio Foundation Model Toward Universal Audio Generation",
    description: "Paper: https://arxiv.org/abs/2310.00704\nCode: https://github.com/yangdongchao/UniAudio\nDemo: https://dongchaoyang.top/UniAudio_demo/",
    videoId: "nho85T68sL4",
    thumbnail: "https://img.youtube.com/vi/nho85T68sL4/maxresdefault.jpg",
    duration: "36:03",
    publishedAt: "2023-10-22",
    views: "1.0K",
    likes: "26"
  },
  {
    title: "QA-LoRA: Quantization-Aware Low-Rank Adaptation of Large Language Models",
    description: "Paper found here: https://arxiv.org/abs/2309.14717v2",
    videoId: "Nmtc_4nIww0",
    thumbnail: "https://img.youtube.com/vi/Nmtc_4nIww0/maxresdefault.jpg",
    duration: "57:42",
    publishedAt: "2023-10-16",
    views: "2.2K",
    likes: "62"
  },
  {
    title: "StreamingLLM - Efficient Streaming Language Models with Attention Sinks Explained",
    description: "Paper found here: https://arxiv.org/abs/2309.17453\n\nCode found here: https://github.com/mit-han-lab/streaming-llm",
    videoId: "f23sUViqxH8",
    thumbnail: "https://img.youtube.com/vi/f23sUViqxH8/maxresdefault.jpg",
    duration: "33:26",
    publishedAt: "2023-10-07",
    views: "2.4K",
    likes: "84"
  },
  {
    title: "FreeU: Free Lunch in Diffusion U-Net Explained",
    description: "Paper found here: https://arxiv.org/abs/2309.11497",
    videoId: "eFmkJ_oEW5s",
    thumbnail: "https://img.youtube.com/vi/eFmkJ_oEW5s/maxresdefault.jpg",
    duration: "28:51",
    publishedAt: "2023-09-24",
    views: "2.4K",
    likes: "68"
  },
  {
    title: "InstaFlow: One Step is Enough for High-Quality Diffusion-Based Text-to-Image Generation Explained",
    description: "Paper found here: https://arxiv.org/abs/2309.06380",
    videoId: "uTpjP_M6PUU",
    thumbnail: "https://img.youtube.com/vi/uTpjP_M6PUU/maxresdefault.jpg",
    duration: "26:25",
    publishedAt: "2023-09-17",
    views: "1.0K",
    likes: "42"
  },
  {
    title: "Llama/Wizard LM Finetuning with Huggingface on RunPod",
    description: "A demo I made to show how to fine-tune a WizardLM model with Huggingface and peft.\nPresentation: https://docs.google.com/presentation/d/17TyDtImkcXnIXwd6CDoYxCXBprvtD_n1I3RlImJg8gQ/edit?usp=sharing\nGi...",
    videoId: "hkt5Nz0buso",
    thumbnail: "https://img.youtube.com/vi/hkt5Nz0buso/maxresdefault.jpg",
    duration: "50:20",
    publishedAt: "2023-09-16",
    views: "3.7K",
    likes: "82"
  },
  {
    title: "2x Faster Language Model Pre-training via Masked Structural Growth",
    description: "Paper found here: https://arxiv.org/abs/2305.02869",
    videoId: "Ndqq0XH5wcw",
    thumbnail: "https://img.youtube.com/vi/Ndqq0XH5wcw/maxresdefault.jpg",
    duration: "50:13",
    publishedAt: "2023-09-10",
    views: "497",
    likes: "16"
  },
  {
    title: "Bayesian Flow Networks (BFN) Explained",
    description: "Paper found here: https://arxiv.org/abs/2308.07037",
    videoId: "kyNCEO24uvc",
    thumbnail: "https://img.youtube.com/vi/kyNCEO24uvc/maxresdefault.jpg",
    duration: "53:53",
    publishedAt: "2023-09-03",
    views: "2.5K",
    likes: "73"
  },
  {
    title: "WizardLM: Empowering Large Language Models to Follow Complex Instructions Explained",
    description: "Paper found here: https://arxiv.org/abs/2304.12244\n\nCode release: https://github.com/nlpxucan/WizardLM",
    videoId: "P0CDVRqS8iA",
    thumbnail: "https://img.youtube.com/vi/P0CDVRqS8iA/maxresdefault.jpg",
    duration: "33:54",
    publishedAt: "2023-08-27",
    views: "1.1K",
    likes: "40"
  },
  {
    title: "From Sparse to Soft Mixtures of Experts Explained",
    description: "Paper found here: https://arxiv.org/abs/2308.00951",
    videoId: "-IBJ1CRO9Zw",
    thumbnail: "https://img.youtube.com/vi/-IBJ1CRO9Zw/maxresdefault.jpg",
    duration: "43:58",
    publishedAt: "2023-08-21",
    views: "3.9K",
    likes: "106"
  },
  {
    title: "BK-SDM: Architecturally Compressed Stable Diffusion for Efficient T2I Generation Explained",
    description: "Paper found here: https://openreview.net/forum?id=bOVydU0XKC",
    videoId: "H4Mn0fcBVXs",
    thumbnail: "https://img.youtube.com/vi/H4Mn0fcBVXs/maxresdefault.jpg",
    duration: "42:15",
    publishedAt: "2023-08-16",
    views: "306",
    likes: "14"
  },
  {
    title: "Direct Preference Optimization (DPO): Your Language Model is Secretly a Reward Model Explained",
    description: "Paper found here: https://arxiv.org/abs/2305.18290",
    videoId: "HCFTXTn1PHA",
    thumbnail: "https://img.youtube.com/vi/HCFTXTn1PHA/maxresdefault.jpg",
    duration: "36:24",
    publishedAt: "2023-08-10",
    views: "18.8K",
    likes: "400"
  },
  {
    title: "Universal and Transferable Adversarial Attacks on Aligned Language Models Explained",
    description: "Paper found here: https://arxiv.org/abs/2307.15043\n\nDemo here: https://llm-attacks.org/",
    videoId: "fy26vj_jGvc",
    thumbnail: "https://img.youtube.com/vi/fy26vj_jGvc/maxresdefault.jpg",
    duration: "31:50",
    publishedAt: "2023-08-06",
    views: "2.6K",
    likes: "59"
  },
  {
    title: "SDXL: Improving Latent Diffusion Models for High-Resolution Image Synthesis Explained",
    description: "Paper found here: https://arxiv.org/abs/2307.01952",
    videoId: "6Xp1xccsG8E",
    thumbnail: "https://img.youtube.com/vi/6Xp1xccsG8E/maxresdefault.jpg",
    duration: "45:45",
    publishedAt: "2023-08-01",
    views: "3.3K",
    likes: "106"
  },
  {
    title: "SDEdit: Guided Image Synthesis and Editing with Stochastic Differential Equations Explained",
    description: "Paper found here: https://arxiv.org/abs/2108.01073",
    videoId: "C_kDJhUQNnY",
    thumbnail: "https://img.youtube.com/vi/C_kDJhUQNnY/maxresdefault.jpg",
    duration: "47:16",
    publishedAt: "2023-07-30",
    views: "1.5K",
    likes: "31"
  },
  {
    title: "ReLoRA: Stack More Layers Differently: High-Rank Training Through Low-Rank Updates Explained",
    description: "Paper found here: https://arxiv.org/abs/2307.05695",
    videoId: "c6EnXjdOmtQ",
    thumbnail: "https://img.youtube.com/vi/c6EnXjdOmtQ/maxresdefault.jpg",
    duration: "35:56",
    publishedAt: "2023-07-26",
    views: "936",
    likes: "36"
  },
  {
    title: "MiniLLM: Knowledge Distillation of Large Language Models",
    description: "Paper found here: https://arxiv.org/abs/2306.08543\n\nCode will be found here: https://github.com/microsoft/LMOps/tree/main/minillm",
    videoId: "fbledYWt_PE",
    thumbnail: "https://img.youtube.com/vi/fbledYWt_PE/maxresdefault.jpg",
    duration: "43:49",
    publishedAt: "2023-07-23",
    views: "6.6K",
    likes: "172"
  },
  {
    title: "RetNet: A Successor to Transformer for Large Language Models Explained",
    description: "Paper found here: https://arxiv.org/abs/2307.08621\n\nCode will be found here soon: https://github.com/microsoft/unilm/tree/master/retnet",
    videoId: "B_iGSeG04qo",
    thumbnail: "https://img.youtube.com/vi/B_iGSeG04qo/maxresdefault.jpg",
    duration: "1:09:57",
    publishedAt: "2023-07-20",
    views: "9.0K",
    likes: "252"
  },
  {
    title: "HyperDreamBooth: HyperNetworks for Fast Personalization of Text-to-Image Explained",
    description: "Paper found here: https://arxiv.org/abs/2307.06949\n\nHere's a helpful Wikipedia article that talks about semi-orthogonal matrices: https://en.wikipedia.org/wiki/Semi-orthogonal_matrix",
    videoId: "ge1SSXouopo",
    thumbnail: "https://img.youtube.com/vi/ge1SSXouopo/maxresdefault.jpg",
    duration: "54:21",
    publishedAt: "2023-07-16",
    views: "514",
    likes: "10"
  },
  {
    title: "Mixture-of-Experts Meets Instruction Tuning: A Winning Combination for LLMs Explained",
    description: "Paper found here: https://arxiv.org/abs/2305.14705",
    videoId: "h7jqxw0ZuAg",
    thumbnail: "https://img.youtube.com/vi/h7jqxw0ZuAg/maxresdefault.jpg",
    duration: "39:17",
    publishedAt: "2023-07-13",
    views: "2.5K",
    likes: "72"
  },
  {
    title: "Voicebox: Text-Guided Multilingual Universal Speech Generation at Scale Explained",
    description: "Paper found here: https://arxiv.org/abs/2306.15687\nDemo found here: https://voicebox.metademolab.com/",
    videoId: "I4YRzP1Y3a8",
    thumbnail: "https://img.youtube.com/vi/I4YRzP1Y3a8/maxresdefault.jpg",
    duration: "1:00:14",
    publishedAt: "2023-07-10",
    views: "709",
    likes: "26"
  },
  {
    title: "LongNet: Scaling Transformers to 1,000,000,000 Tokens Explained",
    description: "Paper found here: https://arxiv.org/abs//2307.02486",
    videoId: "0kdETHUhjAA",
    thumbnail: "https://img.youtube.com/vi/0kdETHUhjAA/maxresdefault.jpg",
    duration: "37:20",
    publishedAt: "2023-07-09",
    views: "1.6K",
    likes: "51"
  },
  {
    title: "Extending Context Window of Large Language Models via Positional Interpolation Explained",
    description: "Paper found here: https://arxiv.org/abs/2306.15595\n\nLooks like there was a discussion about this topic here if interested: https://github.com/ggerganov/llama.cpp/discussions/1965",
    videoId: "oyXdmtHgZFw",
    thumbnail: "https://img.youtube.com/vi/oyXdmtHgZFw/maxresdefault.jpg",
    duration: "29:17",
    publishedAt: "2023-07-07",
    views: "3.7K",
    likes: "86"
  },
  {
    title: "RoFormer: Enhanced Transformer with Rotary Position Embedding Explained",
    description: "Paper found here: https://arxiv.org/abs/2104.09864",
    videoId: "YMcwsLGU_U8",
    thumbnail: "https://img.youtube.com/vi/YMcwsLGU_U8/maxresdefault.jpg",
    duration: "39:52",
    publishedAt: "2023-07-06",
    views: "7.5K",
    likes: "213"
  },
  {
    title: "RoboCat: A Self-Improving Foundation Agent for Robotic Manipulation Explained",
    description: "Paper found at: https://arxiv.org/abs/2306.11706\nDemo here: https://www.deepmind.com/blog/robocat-a-self-improving-robotic-agent",
    videoId: "92LJA3Kydo4",
    thumbnail: "https://img.youtube.com/vi/92LJA3Kydo4/maxresdefault.jpg",
    duration: "37:46",
    publishedAt: "2023-07-02",
    views: "546",
    likes: "16"
  },
  {
    title: "MusicGen: Simple and Controllable Music Generation Explained",
    description: "Paper found here: https://arxiv.org/abs/2306.05284",
    videoId: "5xqUoseyffw",
    thumbnail: "https://img.youtube.com/vi/5xqUoseyffw/maxresdefault.jpg",
    duration: "43:15",
    publishedAt: "2023-06-26",
    views: "5.5K",
    likes: "163"
  },
  {
    title: "Encodec: High Fidelity Neural Audio Compression Explained",
    description: "Paper found here: https://arxiv.org/abs/2210.13438",
    videoId: "-2BS70rDVwk",
    thumbnail: "https://img.youtube.com/vi/-2BS70rDVwk/maxresdefault.jpg",
    duration: "52:55",
    publishedAt: "2023-06-18",
    views: "3.9K",
    likes: "108"
  },
  {
    title: "QLoRA: Efficient Finetuning of Quantized LLMs Explained",
    description: "Paper found here: https://arxiv.org/abs/2305.14314",
    videoId: "C33SwN3Ynp4",
    thumbnail: "https://img.youtube.com/vi/C33SwN3Ynp4/maxresdefault.jpg",
    duration: "29:00",
    publishedAt: "2023-06-05",
    views: "4.3K",
    likes: "178"
  },
  {
    title: "Drag Your GAN: Interactive Point-based Manipulation on the Generative Image Manifold Explained",
    description: "Paper found here: https://arxiv.org/abs/2305.10973",
    videoId: "iG0dwRyYzMg",
    thumbnail: "https://img.youtube.com/vi/iG0dwRyYzMg/maxresdefault.jpg",
    duration: "35:18",
    publishedAt: "2023-05-28",
    views: "619",
    likes: "19"
  },
  {
    title: "Stable/Latent Diffusion - High-Resolution Image Synthesis with Latent Diffusion Models Explained",
    description: "Paper found here: https://arxiv.org/abs/2112.10752",
    videoId: "rC34475rEnw",
    thumbnail: "https://img.youtube.com/vi/rC34475rEnw/maxresdefault.jpg",
    duration: "44:05",
    publishedAt: "2023-04-29",
    views: "16.6K",
    likes: "456"
  },
  {
    title: "LoRA: Low-Rank Adaptation of LLMs Explained",
    description: "LoRA paper can be found here: https://arxiv.org/abs/2106.09685",
    videoId: "_K3HgjnRHCY",
    thumbnail: "https://img.youtube.com/vi/_K3HgjnRHCY/maxresdefault.jpg",
    duration: "27:19",
    publishedAt: "2023-04-26",
    views: "11.5K",
    likes: "364"
  },
  {
    title: "Align your Latents - High-Resolution Video Synthesis Explanation",
    description: "Explanation of the \"Align Your Latents\" paper which generates video from a text prompt. Paper found at: https://arxiv.org/abs/2304.08818",
    videoId: "0vJQY_PY-D8",
    thumbnail: "https://img.youtube.com/vi/0vJQY_PY-D8/maxresdefault.jpg",
    duration: "36:15",
    publishedAt: "2023-04-22",
    views: "2.1K",
    likes: "60"
  },
  {
    title: "Attention Is All You Need Explanation",
    description: "Explaining the Attention is All You Need paper which can be found here:\nhttps://arxiv.org/abs/1706.03762",
    videoId: "w76Dpp7b3B4",
    thumbnail: "https://img.youtube.com/vi/w76Dpp7b3B4/maxresdefault.jpg",
    duration: "1:10:42",
    publishedAt: "2023-02-21",
    views: "2.6K",
    likes: "93"
  },
  {
    title: "ViT: An Image is Worth 16x16 Words Explained",
    description: "Explaining how Vision Transformers (ViTs) work.\n\nhttps://arxiv.org/abs/2010.11929",
    videoId: "YNMk1LIDZi8",
    thumbnail: "https://img.youtube.com/vi/YNMk1LIDZi8/maxresdefault.jpg",
    duration: "37:18",
    publishedAt: "2023-02-21",
    views: "1.1K",
    likes: "33"
  },
  {
    title: "Talking To My AI Girlfriend",
    description: "What's up cutie? The start of every perfect conversation.\n\nMore context:\nhttps://medium.com/p/f951e648aa46\n\nIf you want to try it out:\nhttps://github.com/gmongaras/AI_Girlfriend",
    videoId: "PxsyIjzlcCM",
    thumbnail: "https://img.youtube.com/vi/PxsyIjzlcCM/maxresdefault.jpg",
    duration: "15:33",
    publishedAt: "2023-02-03",
    views: "6.4K",
    likes: "29"
  }
];
